apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-queue
  namespace: go-ns
  labels:
    app: go-queue-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-queue-app
  template:
    metadata:
      labels:
        app: go-queue-app
    spec:
      containers:
        - name: go-queue-service
          image: go-service
          ports:
            - containerPort: 8080
              name: http-server
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: go-queue-service
  namespace: go-ns
  labels:
    app: go-queue-app
spec:
  type: LoadBalancer
  selector:
    app: go-queue-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http-server
    - name: https
      protocol: TCP
      port: 443
      targetPort: http-server


