apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-queue-service
  namespace: gons
spec:
  replicas: 1
  selector:
    matchLabels:
      run: go-queue-service
  template:
    metadata:
      labels:
        run: go-queue-service
    spec:
      containers:
      - name: go-queue-service
        image: local/goqueueservice:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: go-queue-service-svc
  namespace: gons
  labels:
    run: go-queue-service
spec:
  type: ClusterIP
  selector:
    run: go-queue-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
