apiVersion: skaffold/v2beta26
kind: Config

metadata:
  name: ops

build:
  artifacts:
    - image: go-service
      docker:
        dockerfile: .ops/docker/Dockerfile

deploy:
  helm:
    releases:
      - name: rabbitmq
        remoteChart: bitnami/rabbitmq
        version: 8.24.12
        valuesFiles:
          - .ops/helm/values/rabbitmq.yaml
        namespace: go-ns
        createNamespace: true
  kubectl:
    manifests:
    - .ops/k8s/*.yaml

portForward:
  - resourceType: service
    resourceName: rabbitmq
    namespace: go-ns
    port: 15672
    localPort: 15672
  - resourceType: service
    resourceName: go-queue-service
    namespace: go-ns
    port: 8080
    localPort: 8080
