apiVersion: skaffold/v2beta29
kind: Config

metadata:
  name: ops

build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: local/goqueueservice
      docker:
        dockerfile: .ops/docker/Dockerfile

deploy:
  helm:
    releases:
    - name: rabbitmq
      remoteChart: bitnami/rabbitmq
      version: 8.24.13
      valuesFiles:
        - .ops/helm/values/rabbitmq.yaml
      namespace: gons
  kubectl:
    manifests:
    - .ops/k8s/*.yaml

portForward:
  - resourceType: service
    resourceName: rabbitmq
    namespace: gons
    port: 5672
    localPort: 5672
