apiVersion: skaffold/v2beta26
kind: Config

metadata:
  name: ops

build:
  artifacts:
    - image: go-queue
      docker:
        dockerfile: .ops/docker/Dockerfile

deploy:
  helm:
    releases:
    - name: rabbitmq
      remoteChart: bitnami/rabbitmq
      version: 8.18.1
      valuesFiles:
        - .ops/helm/values/rabbitmq.yaml
      namespace: go-ns
  kubectl:
    manifests:
    - .ops/k8s/*.yaml

portForward:
  - resourceType: service
    resourceName: rabbitmq
    namespace: go-ns
    port: 5672
    localPort: 5672
