apiVersion: skaffold/v3
kind: Config

metadata:
  name: ops

build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: local/goqueueservice
      docker:
        dockerfile: .ops/docker/Dockerfile

manifests:
  rawYaml:
    - .ops/k8s/*.yaml

deploy:
  helm:
    releases:
    - name: rabbitmq
      remoteChart: bitnami/rabbitmq
      version: 11.13.0
      valuesFiles:
        - .ops/helm/values/rabbitmq.yaml
      namespace: gons
  kubectl: {}

portForward:
  - resourceType: service
    resourceName: rabbitmq
    namespace: gons
    port: 5672
    localPort: 5672
